In [2]:
import numpy as np
from scipy.linalg import svd
a=np.arange(12).reshape(3,4)
print(a,'\n')
a,b,c=svd(a)
print(a,'\n')
print(b,'\n')
print(c,'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[-0.1473065  -0.90090739  0.40824829]
 [-0.50027528 -0.2881978  -0.81649658]
 [-0.85324407  0.32451178  0.40824829]] 

[2.24092982e+01 1.95534034e+00 7.68985043e-16] 

[[-0.39390139 -0.46087474 -0.5278481  -0.59482145]
 [ 0.73813393  0.29596363 -0.14620666 -0.58837696]
 [-0.50775138  0.52390687  0.47544042 -0.4915959 ]
 [-0.20539847  0.65232016 -0.68844492  0.24152322]] 

