In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6]).reshape((2,3))
print(a)
print('\nTRANSPOSE\n')
c=np.transpose(a)
print(c)

[[1 2 3]
 [4 5 6]]

TRANSPOSE

[[1 4]
 [2 5]
 [3 6]]


In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6]).reshape((2,3))
print('\nMATRIX A\n',a)
b=np.array([1,2,3,4,5,6]).reshape((3,2))
print('\nMATRIX B\n',b)
c=np.dot(a,b)
print('\nMATRIX MULTIPLICATION\n')
print(c)


MATRIX A
 [[1 2 3]
 [4 5 6]]

MATRIX B
 [[1 2]
 [3 4]
 [5 6]]

MATRIX MULTIPLICATION

[[22 28]
 [49 64]]
